#!/bin/bash

export DEVICE=$@
JOBS=${JOBS:=12}

if [ -z $DEVICE ]; then
	echo "Please specify a device codename"
	exit 0
fi

if [ -d $DEVICE ]; then
	echo "*****************************************"
	echo "I: Configuring for device $DEVICE"
	echo "*****************************************"

	export REPO_ROOT=../..

	# Test if there is already a device configured and the folder exists
	if [ -f $REPO_ROOT/.repo/local_manifests/device.xml ]; then
		rm $REPO_ROOT/.repo/local_manifests/device.xml
	elif ! [ -d $REPO_ROOT/.repo/local_manifests/ ]; then
		mkdir $REPO_ROOT/.repo/local_manifests/
	fi

	# Link the device manifest to the local_manifests folder
	ln $DEVICE/manifest.xml $REPO_ROOT/.repo/local_manifests/device.xml

	# Synchronize new new sources
	repo sync --network-only -c -j$JOBS
	repo sync --local-only -c -j$JOBS

	# Set up build environment
	source $REPO_ROOT/build/envsetup.sh

	# Configure build environment for the specified device
	breakfast $DEVICE
	lunch lineage_${DEVICE}-userdebug
fi
